
import React, { useState } from 'react';
import { GoogleGenAI } from "@google/genai";

const BespokeStudio: React.FC = () => {
  const [prompt, setPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = async () => {
    if (!prompt.trim()) return;

    setIsGenerating(true);
    setError(null);

    try {
      const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [
            {
              text: `A high-end, luxury, professional commercial photograph for an e-commerce store. Aesthetic: minimal, elegant, soft beige lighting, premium quality. Subject: ${prompt}`,
            },
          ],
        },
        config: {
          imageConfig: {
            aspectRatio: "16:9"
          }
        }
      });

      let foundImage = false;
      if (response.candidates?.[0]?.content?.parts) {
        for (const part of response.candidates[0].content.parts) {
          if (part.inlineData) {
            const base64EncodeString = part.inlineData.data;
            setGeneratedImage(`data:image/png;base64,${base64EncodeString}`);
            foundImage = true;
            break;
          }
        }
      }

      if (!foundImage) {
        throw new Error("No image was generated by the model.");
      }
    } catch (err: any) {
      console.error(err);
      setError("The artisan model is currently busy. Please try your request again in a moment.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <section className="bg-white py-24 border-y border-beige-100">
      <div className="max-w-6xl mx-auto px-4">
        <div className="flex flex-col lg:flex-row items-center gap-16">
          <div className="flex-1 space-y-8">
            <div className="space-y-4">
              <span className="text-[10px] tracking-[0.4em] uppercase text-beige-800 font-bold">The Creative Studio</span>
              <h2 className="text-5xl font-serif text-charcoal-900 leading-tight">
                Bespoke Vision <br /> 
                <span className="italic">Powered by Intelligence</span>
              </h2>
              <p className="text-gray-500 max-w-md leading-relaxed">
                Describe your dream piece or a custom atmospheric scene, and our AI creative engine will visualize it instantly in our signature luxury aesthetic.
              </p>
            </div>

            <div className="space-y-4">
              <div className="relative">
                <input 
                  type="text"
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  placeholder="e.g., A diamond necklace resting on silk..."
                  className="w-full bg-beige-50 border-b border-beige-300 py-4 px-2 outline-none focus:border-charcoal-800 transition-all font-serif italic text-lg text-charcoal-800"
                  disabled={isGenerating}
                />
              </div>
              <button 
                onClick={handleGenerate}
                disabled={isGenerating || !prompt}
                className={`group flex items-center gap-4 px-10 py-5 bg-charcoal-900 text-white text-[10px] font-bold tracking-[0.3em] uppercase transition-all duration-500 ${isGenerating ? 'opacity-50 cursor-not-allowed' : 'hover:bg-charcoal-800'}`}
              >
                {isGenerating ? (
                  <span className="flex items-center gap-3">
                    <svg className="animate-spin h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                    Mastering Visuals...
                  </span>
                ) : (
                  <>
                    Visualize Concepts
                    <svg className="w-4 h-4 transform group-hover:translate-x-1 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M14 5l7 7m0 0l-7 7m7-7H3" />
                    </svg>
                  </>
                )}
              </button>
              {error && <p className="text-red-500 text-xs mt-2 italic">{error}</p>}
            </div>
          </div>

          <div className="flex-1 w-full">
            <div className="aspect-video bg-beige-50 relative overflow-hidden rounded-sm border border-beige-200 group">
              {generatedImage ? (
                <img 
                  src={generatedImage} 
                  alt="Generated Luxury Concept" 
                  className="w-full h-full object-cover animate-fade-in"
                />
              ) : (
                <div className="absolute inset-0 flex flex-col items-center justify-center p-12 text-center text-beige-400">
                  <div className="w-20 h-20 mb-6 border border-beige-200 rounded-full flex items-center justify-center opacity-50">
                     <span className="text-3xl">✨</span>
                  </div>
                  <p className="font-serif italic text-lg mb-2">Awaiting your vision</p>
                  <p className="text-[10px] uppercase tracking-widest max-w-xs">Your custom generation will appear here in high fidelity</p>
                </div>
              )}
              
              {isGenerating && (
                <div className="absolute inset-0 bg-white/60 backdrop-blur-sm flex items-center justify-center">
                  <div className="w-full max-w-xs px-8">
                     <div className="h-0.5 bg-beige-100 overflow-hidden">
                        <div className="h-full bg-charcoal-800 animate-[loading-bar_2s_infinite]" />
                     </div>
                     <p className="text-[8px] tracking-[0.4em] uppercase text-charcoal-800 mt-4 text-center">Architecting Pixels</p>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
      <style>{`
        @keyframes loading-bar {
          0% { transform: translateX(-100%); }
          100% { transform: translateX(100%); }
        }
      `}</style>
    </section>
  );
};

export default BespokeStudio;
